// <auto-generated />
using System;
using DevExtremeAspNetCoreApp1.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevExtremeAspNetCoreApp1.Migrations
{
    [DbContext(typeof(Context1))]
    partial class Context1ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DevExtremeAspNetCoreApp1.Entities.Birim", b =>
                {
                    b.Property<int>("YoksisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YoksisId"), 1L, 1);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdIng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Durum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnumBirimTuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IliskiliYoksisId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisaAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("THE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UstYoksisId")
                        .HasColumnType("int");

                    b.HasKey("YoksisId");

                    b.ToTable("birim");
                });

            modelBuilder.Entity("DevExtremeAspNetCoreApp1.Entities.FilePath", b =>
                {
                    b.Property<int>("FilePathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilePathId"), 1L, 1);

                    b.Property<int>("KararId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FilePathId");

                    b.HasIndex("KararId");

                    b.ToTable("filePaths");
                });

            modelBuilder.Entity("DevExtremeAspNetCoreApp1.Entities.Karar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BirimId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("kararlar");
                });

            modelBuilder.Entity("DevExtremeAspNetCoreApp1.Entities.Kisi", b =>
                {
                    b.Property<int>("KisiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KisiId"), 1L, 1);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KisiId");

                    b.ToTable("kisiler");
                });

            modelBuilder.Entity("DevExtremeAspNetCoreApp1.Entities.PersonelGorev", b =>
                {
                    b.Property<int>("PGID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PGID"), 1L, 1);

                    b.Property<DateTime>("BaslamaTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("BirimId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BitisTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("KisiId")
                        .HasColumnType("int");

                    b.Property<int>("TanimId")
                        .HasColumnType("int");

                    b.HasKey("PGID");

                    b.HasIndex("KisiId");

                    b.HasIndex("TanimId");

                    b.ToTable("personelGorevler");
                });

            modelBuilder.Entity("DevExtremeAspNetCoreApp1.Entities.Tanim", b =>
                {
                    b.Property<int>("TanimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TanimId"), 1L, 1);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kategori")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TanimId");

                    b.ToTable("tanimlar");
                });

            modelBuilder.Entity("DevExtremeAspNetCoreApp1.Entities.FilePath", b =>
                {
                    b.HasOne("DevExtremeAspNetCoreApp1.Entities.Karar", "Karar")
                        .WithMany("Files")
                        .HasForeignKey("KararId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Karar");
                });

            modelBuilder.Entity("DevExtremeAspNetCoreApp1.Entities.PersonelGorev", b =>
                {
                    b.HasOne("DevExtremeAspNetCoreApp1.Entities.Kisi", "Kisi")
                        .WithMany()
                        .HasForeignKey("KisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevExtremeAspNetCoreApp1.Entities.Tanim", "Tanim")
                        .WithMany()
                        .HasForeignKey("TanimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kisi");

                    b.Navigation("Tanim");
                });

            modelBuilder.Entity("DevExtremeAspNetCoreApp1.Entities.Karar", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
